ivar_pattern: amplicon_*/02_assembly_results/05_ivar_tables/*/*.tsv
fasta_pattern: amplicon_*/02_assembly_results/03_contigs/**/*_contig*_consensus.fa
tidyvcf_pattern: amplicon_**/02_assembly_results/04_contig_VCFs/**/*.tvcf.tsv